/* Pack Protocol C API - Auto-generated by cbindgen */

#ifndef PACK_PROTOCOL_H
#define PACK_PROTOCOL_H

/* WARNING: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum PackFfiError {
    OK = 0,
    INVALID_ARGUMENT = 1,
    INVALID_KEY = 2,
    INVALID_SIGNATURE = 3,
    INVALID_MESSAGE = 4,
    INVALID_MAC = 5,
    UNTRUSTED_IDENTITY = 6,
    NO_SESSION = 7,
    DUPLICATE_MESSAGE = 8,
    EXPIRED_CERTIFICATE = 9,
    INVALID_CERTIFICATE = 10,
    TOO_MANY_SKIPPED_MESSAGES = 11,
    INTERNAL_ERROR = 255,
} PackFfiError;

typedef int32_t (*LoadSessionCb)(void *ctx,
                                 const uint8_t *name,
                                 uintptr_t name_len,
                                 uint32_t device_id,
                                 uint8_t *out_buf,
                                 uintptr_t buf_len,
                                 uintptr_t *out_len);

typedef int32_t (*StoreSessionCb)(void *ctx,
                                  const uint8_t *name,
                                  uintptr_t name_len,
                                  uint32_t device_id,
                                  const uint8_t *data,
                                  uintptr_t data_len);

typedef int32_t (*GetIdentityKeyPairCb)(void *ctx, uint8_t *out_public, uint8_t *out_private);

typedef int32_t (*GetRegistrationIdCb)(void *ctx, uint32_t *out_id);

typedef int32_t (*SaveIdentityCb)(void *ctx,
                                  const uint8_t *name,
                                  uintptr_t name_len,
                                  uint32_t device_id,
                                  const uint8_t *identity,
                                  uint8_t *out_changed);

typedef int32_t (*IsTrustedIdentityCb)(void *ctx,
                                       const uint8_t *name,
                                       uintptr_t name_len,
                                       uint32_t device_id,
                                       const uint8_t *identity,
                                       uint8_t direction,
                                       uint8_t *out_trusted);

typedef int32_t (*GetIdentityCb)(void *ctx,
                                 const uint8_t *name,
                                 uintptr_t name_len,
                                 uint32_t device_id,
                                 uint8_t *out_identity,
                                 uint8_t *out_found);

typedef int32_t (*GetPreKeyCb)(void *ctx, uint32_t id, uint8_t *out_public, uint8_t *out_private);

typedef int32_t (*RemovePreKeyCb)(void *ctx, uint32_t id);

typedef int32_t (*GetSignedPreKeyCb)(void *ctx,
                                     uint32_t id,
                                     uint8_t *out_public,
                                     uint8_t *out_private,
                                     uint8_t *out_signature,
                                     uint64_t *out_timestamp);

typedef int32_t (*StoreSenderKeyCb)(void *ctx,
                                    const uint8_t *sender_name,
                                    uintptr_t sender_name_len,
                                    uint32_t sender_device_id,
                                    const uint8_t *distribution_id,
                                    uintptr_t distribution_id_len,
                                    const uint8_t *data,
                                    uintptr_t data_len);

typedef int32_t (*LoadSenderKeyCb)(void *ctx,
                                   const uint8_t *sender_name,
                                   uintptr_t sender_name_len,
                                   uint32_t sender_device_id,
                                   const uint8_t *distribution_id,
                                   uintptr_t distribution_id_len,
                                   uint8_t *out_buf,
                                   uintptr_t buf_len,
                                   uintptr_t *out_len);

typedef struct PackSessionStoreCallbacks {
    void *ctx;
    LoadSessionCb load_session;
    StoreSessionCb store_session;
    GetIdentityKeyPairCb get_identity_key_pair;
    GetRegistrationIdCb get_registration_id;
    SaveIdentityCb save_identity;
    IsTrustedIdentityCb is_trusted_identity;
    GetIdentityCb get_identity;
    GetPreKeyCb get_pre_key;
    RemovePreKeyCb remove_pre_key;
    GetSignedPreKeyCb get_signed_pre_key;
    StoreSenderKeyCb store_sender_key;
    LoadSenderKeyCb load_sender_key;
} PackSessionStoreCallbacks;

enum PackFfiError pack_identity_key_pair_generate(IdentityKeyPair **out);

void pack_identity_key_pair_destroy(IdentityKeyPair *handle);

enum PackFfiError pack_identity_key_pair_get_public(const IdentityKeyPair *handle,
                                                    uint8_t *out_buf,
                                                    uintptr_t buf_len,
                                                    uintptr_t *out_len);

enum PackFfiError pack_identity_key_pair_sign(const IdentityKeyPair *handle,
                                              const uint8_t *message,
                                              uintptr_t message_len,
                                              uint8_t *out_sig,
                                              uintptr_t sig_buf_len,
                                              uintptr_t *out_sig_len);

enum PackFfiError pack_identity_key_from_bytes(const uint8_t *data,
                                               uintptr_t data_len,
                                               IdentityKey **out);

void pack_identity_key_destroy(IdentityKey *handle);

enum PackFfiError pack_identity_key_get_bytes(const IdentityKey *handle,
                                              uint8_t *out_buf,
                                              uintptr_t buf_len,
                                              uintptr_t *out_len);

enum PackFfiError pack_identity_key_verify(const IdentityKey *handle,
                                           const uint8_t *message,
                                           uintptr_t message_len,
                                           const uint8_t *signature,
                                           uintptr_t signature_len);

enum PackFfiError pack_keypair_generate(KeyPair **out);

void pack_keypair_destroy(KeyPair *handle);

enum PackFfiError pack_keypair_get_public(const KeyPair *handle,
                                          uint8_t *out_buf,
                                          uintptr_t buf_len,
                                          uintptr_t *out_len);

enum PackFfiError pack_fingerprint_generate(const uint8_t *local_id,
                                            uintptr_t local_id_len,
                                            const IdentityKey *local_key,
                                            const uint8_t *remote_id,
                                            uintptr_t remote_id_len,
                                            const IdentityKey *remote_key,
                                            Fingerprint **out);

void pack_fingerprint_destroy(Fingerprint *handle);

enum PackFfiError pack_fingerprint_display(const Fingerprint *handle,
                                           uint8_t *out_buf,
                                           uintptr_t buf_len,
                                           uintptr_t *out_len);

enum PackFfiError pack_fingerprint_scannable_bytes(const Fingerprint *handle,
                                                   uint8_t *out_buf,
                                                   uintptr_t buf_len,
                                                   uintptr_t *out_len);

enum PackFfiError pack_scannable_fingerprint_verify(const uint8_t *ours,
                                                    uintptr_t ours_len,
                                                    const uint8_t *theirs,
                                                    uintptr_t theirs_len,
                                                    bool *out_match);

enum PackFfiError pack_sealed_sender_encrypt(const IdentityKeyPair *sender_identity,
                                             const uint8_t *sender_cert_data,
                                             uintptr_t sender_cert_len,
                                             const IdentityKey *recipient_key,
                                             const uint8_t *inner_message,
                                             uintptr_t inner_message_len,
                                             uint64_t current_time,
                                             uint8_t *out_buf,
                                             uintptr_t buf_len,
                                             uintptr_t *out_len);

enum PackFfiError pack_sealed_sender_decrypt(const IdentityKeyPair *our_identity,
                                             const uint8_t *ciphertext,
                                             uintptr_t ciphertext_len,
                                             const uint8_t *trust_root_data,
                                             uintptr_t trust_root_len,
                                             uint64_t current_time,
                                             uint8_t *out_sender_uuid_buf,
                                             uintptr_t sender_uuid_buf_len,
                                             uintptr_t *out_sender_uuid_len,
                                             uint8_t *out_message_buf,
                                             uintptr_t message_buf_len,
                                             uintptr_t *out_message_len);

enum PackFfiError pack_session_encrypt(const struct PackSessionStoreCallbacks *callbacks,
                                       const uint8_t *remote_name,
                                       uintptr_t remote_name_len,
                                       uint32_t remote_device_id,
                                       const uint8_t *plaintext,
                                       uintptr_t plaintext_len,
                                       uint8_t *out_buf,
                                       uintptr_t buf_len,
                                       uintptr_t *out_len);

enum PackFfiError pack_session_decrypt(const struct PackSessionStoreCallbacks *callbacks,
                                       const uint8_t *remote_name,
                                       uintptr_t remote_name_len,
                                       uint32_t remote_device_id,
                                       const uint8_t *ciphertext,
                                       uintptr_t ciphertext_len,
                                       uint8_t *out_buf,
                                       uintptr_t buf_len,
                                       uintptr_t *out_len);

enum PackFfiError pack_session_process_pre_key_message(const struct PackSessionStoreCallbacks *callbacks,
                                                       const uint8_t *our_name,
                                                       uintptr_t our_name_len,
                                                       uint32_t our_device_id,
                                                       const uint8_t *remote_name,
                                                       uintptr_t remote_name_len,
                                                       uint32_t remote_device_id,
                                                       const uint8_t *message,
                                                       uintptr_t message_len,
                                                       uint8_t *out_buf,
                                                       uintptr_t buf_len,
                                                       uintptr_t *out_len);

enum PackFfiError pack_session_initiate(const uint8_t *our_name,
                                        uintptr_t our_name_len,
                                        uint32_t our_device_id,
                                        const IdentityKeyPair *our_identity,
                                        uint32_t registration_id,
                                        const uint8_t *remote_name,
                                        uintptr_t remote_name_len,
                                        uint32_t remote_device_id,
                                        const PreKeyBundle *bundle,
                                        const uint8_t *first_message,
                                        uintptr_t first_message_len,
                                        PackSession **out_session,
                                        uint8_t *out_msg_buf,
                                        uintptr_t msg_buf_len,
                                        uintptr_t *out_msg_len);

enum PackFfiError pack_session_respond(const uint8_t *our_name,
                                       uintptr_t our_name_len,
                                       uint32_t our_device_id,
                                       const IdentityKeyPair *our_identity,
                                       uint32_t registration_id,
                                       const uint8_t *remote_name,
                                       uintptr_t remote_name_len,
                                       uint32_t remote_device_id,
                                       const SignedPreKey *signed_pre_key,
                                       const OneTimePreKey *one_time_pre_key,
                                       const uint8_t *pre_key_message,
                                       uintptr_t pre_key_message_len,
                                       PackSession **out_session,
                                       uint8_t *out_pt_buf,
                                       uintptr_t pt_buf_len,
                                       uintptr_t *out_pt_len);

void pack_session_destroy(PackSession *handle);

enum PackFfiError pack_session_encrypt_msg(PackSession *handle,
                                           const uint8_t *plaintext,
                                           uintptr_t plaintext_len,
                                           uint8_t *out_buf,
                                           uintptr_t buf_len,
                                           uintptr_t *out_len);

enum PackFfiError pack_session_decrypt_msg(PackSession *handle,
                                           const uint8_t *ciphertext,
                                           uintptr_t ciphertext_len,
                                           uint8_t *out_buf,
                                           uintptr_t buf_len,
                                           uintptr_t *out_len);

enum PackFfiError pack_session_decrypt_auto(PackSession *handle,
                                            const uint8_t *ciphertext,
                                            uintptr_t ciphertext_len,
                                            const SignedPreKey *signed_pre_key,
                                            const OneTimePreKey *one_time_pre_key,
                                            uint8_t *out_buf,
                                            uintptr_t buf_len,
                                            uintptr_t *out_len);

enum PackFfiError pack_group_session_create_sender(const uint8_t *distribution_id,
                                                   uintptr_t distribution_id_len,
                                                   PackGroupSession **out_session,
                                                   uint8_t *out_dist_buf,
                                                   uintptr_t dist_buf_len,
                                                   uintptr_t *out_dist_len);

void pack_group_session_destroy(PackGroupSession *handle);

enum PackFfiError pack_sealed_sender_encrypt_msg(const IdentityKeyPair *sender_identity,
                                                 const uint8_t *sender_cert_data,
                                                 uintptr_t sender_cert_len,
                                                 const uint8_t *recipient_key_data,
                                                 uint64_t current_time,
                                                 const uint8_t *inner_message,
                                                 uintptr_t inner_message_len,
                                                 uint8_t *out_buf,
                                                 uintptr_t buf_len,
                                                 uintptr_t *out_len);

enum PackFfiError pack_sealed_sender_decrypt_msg(const IdentityKeyPair *our_identity,
                                                 const uint8_t *ciphertext,
                                                 uintptr_t ciphertext_len,
                                                 const uint8_t *trust_root_data,
                                                 uint64_t current_time,
                                                 uint8_t *out_sender_uuid_buf,
                                                 uintptr_t sender_uuid_buf_len,
                                                 uintptr_t *out_sender_uuid_len,
                                                 uint8_t *out_message_buf,
                                                 uintptr_t message_buf_len,
                                                 uintptr_t *out_message_len);

#endif  /* PACK_PROTOCOL_H */
