// Wire format using protobuf-generated types
// Generated by prost from proto/pack.proto and proto/content.proto

#[allow(dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/pack.rs"));
}

pub mod content {
    include!(concat!(env!("OUT_DIR"), "/pack.content.rs"));
}

pub use generated::*;
